this worksheets is part of the [mlvu machine learning course](https://mlvu.github.io)<br>
setting up your environment: https://bit.ly/3bzpn5C

For this worksheet, we'll need to install the pandas package. Run the cell below, or run ```pip install pandas``` in the terminal/command-line/command prompt.

In [7]:
#!pip install pandas

# Worksheet 3: Pandas

Pandas is a python package for data analysis. Where numpy is a package built around a the data structure of a <em>matrix</em>, pandas is a package built around the data structure of a _dataframe_. A dataframe is a lot like a matrix, with some key differences:

* In a data frame, the columns have header names. 
* Different datatypes (int, string, boolean) are allowed within the same dataframe. Each column has its own datatype

In short, dataframes represent datasets of the kind we've seen in the lectures: an instance per row, and a feature per column. 

Pandas is designed to work together with numpy and matplotlib. Let's import all of them

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

To explore Pandas we'll import the ANSUR II dataset (we also used this to create the examples in the first lecture). ANSUR II is an _anthropometric_ dataset: it contains body measurements. ANSUR II contains 108 measurements for about 4000 men and about 2000 women (all US soldiers).

We'll start by reading the data. Like numpy, pandas has a function for reading CSV files. Pandas' function is much more robust, and much less likely to give you trouble. It does come with [a lot of options](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html), so you may have to try a few things before you get it to read your data accurately.

ANSUR II comes in two separate tables: one for male soldiers, and one for female soldiers:

In [9]:
female = pd.read_csv('./ansur/ANSUR II FEMALE Public.csv')
male = pd.read_csv('./ansur/ANSUR II MALE Public.csv')

All the warnings from the first two social impact videos, and from the fourth lecture apply here. This is not a sample that is representative of the population, and the gender class is a sensitive attribute that is poorly captured by two classes.

```male``` and ```female``` are pandas DataFrame objects. Jupyter notebooks will print these as tables:

In [10]:
male

,subjectid,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,Branch,PrimaryMOS,SubjectsBirthLocation,SubjectNumericRace,Ethnicity,DODRace,Age,Heightin,Weightlbs,WritingPreference
0,10027,266,1467,337,222,1347,253,202,401,369,...,Combat Arms,19D,North Dakota,1,NaN,1,41,71,180,Right hand
1,10032,233,1395,326,220,1293,245,193,394,338,...,Combat Support,68W,New York,1,NaN,1,35,68,160,Left hand
2,10033,287,1430,341,230,1327,256,196,427,408,...,Combat Support,68W,New York,2,NaN,2,42,68,205,Left hand
3,10092,234,1347,310,230,1239,262,199,401,359,...,Combat Service Support,88M,Wisconsin,1,NaN,1,31,66,175,Right hand
4,10093,250,1585,372,247,1478,267,224,435,356,...,Combat Service Support,92G,North Carolina,2,NaN,2,21,77,213,Right hand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4077,29442,235,1353,312,216,1263,228,193,384,318,...,Combat Arms,11B,Colorado,51,Blackfoot Cherokee Choctaw,1,22,67,160,Right hand
4078,29443,247,1473,336,234,1346,253,196,428,374,...,Combat Arms,91B,Oklahoma,1,NaN,1,22,71,194,Right hand
4079,29447,264,1394,313,227,1280,245,193,407,367,...,Combat Arms,13B,Oklahoma,1,NaN,1,23,67,186,Right hand
4080,29451,203,1417,327,223,1314,250,196,419,365,...,Combat Arms,13P,Oklahoma,1,NaN,1,22,69,165,Right hand
4081,29452,327,1523,358,226,1408,269,225,442,379,...,Combat Arms,92Y,Oklahoma,1,NaN,1,38,73,218,Right hand

These are big dataframes. Pandas can give us some quick summary statistics per column very easily.

In [11]:
male.describe()

,subjectid,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,waistfrontlengthsitting,waistheightomphalion,weightkg,wristcircumference,wristheight,SubjectNumericRace,DODRace,Age,Heightin,Weightlbs
count,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,...,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000
mean,20003.370897,254.650906,1440.736894,335.244488,229.343949,1329.082068,252.017148,200.935081,415.675649,358.135718,...,387.642822,1056.485301,855.239588,175.916707,847.511514,8.973542,1.534052,30.158991,70.035767,188.004900
std,6568.435122,37.327178,63.287242,17.482795,14.649102,59.516123,12.936131,10.470947,19.161654,34.618093,...,29.349007,52.154671,142.206992,8.955055,41.655628,83.012638,0.958815,8.810118,2.947419,29.941869
min,10027.000000,163.000000,1194.000000,270.000000,156.000000,1106.000000,186.000000,156.000000,337.000000,246.000000,...,293.000000,876.000000,393.000000,141.000000,695.000000,1.000000,1.000000,17.000000,60.000000,0.000000
25%,14270.250000,227.000000,1398.000000,324.000000,219.250000,1289.000000,243.000000,194.000000,403.000000,335.000000,...,367.000000,1020.000000,756.000000,170.000000,819.000000,1.000000,1.000000,23.000000,68.000000,168.000000
50%,17236.500000,251.000000,1439.000000,335.000000,228.000000,1328.000000,252.000000,201.000000,415.000000,357.000000,...,386.000000,1055.000000,846.000000,176.000000,847.000000,1.000000,1.000000,28.000000,70.000000,185.000000
75%,27315.750000,279.000000,1481.000000,346.000000,239.000000,1367.000000,261.000000,208.000000,428.000000,380.000000,...,407.000000,1090.000000,944.000000,182.000000,875.000000,2.000000,2.000000,36.000000,72.000000,207.000000
max,29452.000000,451.000000,1683.000000,393.000000,293.000000,1553.000000,306.000000,245.000000,489.000000,490.000000,...,494.000000,1245.000000,1442.000000,216.000000,1009.000000,4251.000000,8.000000,58.000000,94.000000,321.000000


In pandas these columns are called <em>Series</em>, and a dataframe is basically a list of Series objects with the same length (indexed in various ways for efficient access).

Let's have a look at all the available measurements.

In [12]:
for i, col in enumerate(female.columns):
    print(i, col)

0 SubjectId
1 abdominalextensiondepthsitting
2 acromialheight
3 acromionradialelength
4 anklecircumference
5 axillaheight
6 balloffootcircumference
7 balloffootlength
8 biacromialbreadth
9 bicepscircumferenceflexed
10 bicristalbreadth
11 bideltoidbreadth
12 bimalleolarbreadth
13 bitragionchinarc
14 bitragionsubmandibulararc
15 bizygomaticbreadth
16 buttockcircumference
17 buttockdepth
18 buttockheight
19 buttockkneelength
20 buttockpopliteallength
21 calfcircumference
22 cervicaleheight
23 chestbreadth
24 chestcircumference
25 chestdepth
26 chestheight
27 crotchheight
28 crotchlengthomphalion
29 crotchlengthposterioromphalion
30 earbreadth
31 earlength
32 earprotrusion
33 elbowrestheight
34 eyeheightsitting
35 footbreadthhorizontal
36 footlength
37 forearmcenterofgriplength
38 forearmcircumferenceflexed
39 forearmforearmbreadth
40 forearmhandlength
41 functionalleglength
42 handbreadth
43 handcircumference
44 handlength
45 headbreadth
46 headcircumference
47 headlength
48 heelanklecircumference
49 heelbreadth
50 hipbreadth
51 hipbreadthsitting
52 iliocristaleheight
53 interpupillarybreadth
54 interscyei
55 interscyeii
56 kneeheightmidpatella
57 kneeheightsitting
58 lateralfemoralepicondyleheight
59 lateralmalleolusheight
60 lowerthighcircumference
61 mentonsellionlength
62 neckcircumference
63 neckcircumferencebase
64 overheadfingertipreachsitting
65 palmlength
66 poplitealheight
67 radialestylionlength
68 shouldercircumference
69 shoulderelbowlength
70 shoulderlength
71 sittingheight
72 sleevelengthspinewrist
73 sleeveoutseam
74 span
75 stature
76 suprasternaleheight
77 tenthribheight
78 thighcircumference
79 thighclearance
80 thumbtipreach
81 tibialheight
82 tragiontopofhead
83 trochanterionheight
84 verticaltrunkcircumferenceusa
85 waistbacklength
86 waistbreadth
87 waistcircumference
88 waistdepth
89 waistfrontlengthsitting
90 waistheightomphalion
91 weightkg
92 wristcircumference
93 wristheight
94 Gender
95 Date
96 Installation
97 Component
98 Branch
99 PrimaryMOS
100 SubjectsBirthLocation
101 SubjectNumericRace
102 Ethnicity
103 DODRace
104 Age
105 Heightin
106 Weightlbs
107 WritingPreference

Each column name with a lowercase letter represents a physical measurement. Some of these are quite technical (like <em>bizygomaticbreadth</em>). The dataset comes with a very helpful document that shows what each measurement means (and how it should be performed). It's [included with the worksheets](./ansur/Hotzman_2011_ANSURIII_Measurements_a548497.pdf). Scroll down to section 6.4 for the description of the measurements.

Once the dataframe is loaded, you can refer to the columns by name as python objects. For instance:

In [13]:
male.stature

0       1776
1       1702
2       1735
3       1655
4       1914
        ...
4077    1688
4078    1765
4079    1690
4080    1718
4081    1828
Name: stature, Length: 4082, dtype: int64

Jupyter notebooks even gives you dynamic autocomplete. Try putting your cursor at the end of the next line and pressing the ```TAB``` button on your keyboard (it may take a second).

In [14]:
female.

SyntaxError: invalid syntax (3576666339.py, line 1)

We can now easily do scatterplots of different measurements. Let's plot the ```stature``` (height) against the ```span``` (distance between outstretched arms).

In [ ]:
plt.scatter(female.stature, female.span, color='red')
plt.scatter(male.stature, male.span, color='blue');

Even if we make the points transparent (```alpha=0.1```) and small (```s=1```), it's quite a dense cloud. We can easily select a small subset by [slicing](https://www.pythoncentral.io/how-to-slice-listsarrays-and-tuples-in-python/):

In [ ]:
male[:3]

Note that slicing like this only works over the rows. We can't do ```male[:3, 5:12]```, like we could in numpy.

For now, we know enough to plot a small subset of the data.

In [ ]:
female_sub = female[:50]
male_sub = male[:50]

plt.scatter(female_sub.stature, female_sub.span, color='red')
plt.scatter(male_sub.stature, male_sub.span, color='blue');

To select a set of columns, the best method is to pass a list of strings containing column names. The result is another dataframe.

In [ ]:
male[['bicepscircumferenceflexed', 'Age']]

### Simple arithmetic

Like numpy, pandas objects overload basic arithmetic operations. For instance, the units in this dataset are in millimeters, which is a little hard to read. To convert them to meters, we can simply multiply by 0.001.

In [ ]:
stat = female.stature * 0.001
span = female.span * 0.001

plt.scatter(stat, span);

plt.xlabel('height (m)')
plt.ylabel('span (m)');

### Descriptive statistics

For most descriptive statistics, pandas provides member functions:

In [ ]:
print('mean           ', female.stature.mean())
print('std dev.       ', female.stature.std())
print('median         ', female.stature.median())
print('standard error ', female.stature.sem())

### Concatenating and sampling

To perform the classification task from the first lecture (predicting gender from physical measurements), we want the male and female data in a single dataframe. To accomplish this, we can concatenate the two dataframes

In [ ]:
people = pd.concat([male, female])

This gives us a dataset of all the male measurements first, and then all the female measurements. For many reasons, it's helpful to shuffle these, so that the order is random. The simplest way to do this is pandas is to _sample_ a new dataframe (without replacement) of the same size:

In [ ]:
people = people.sample(frac=1)
people[:5].Gender

Note that the row indices from the original dataframe are retained and shuffled as well. For our purposes this doesn't matter.

## Performing Classification

### Categories and codes

To perform classification on this dataset, we need to convert the target value from strings to categorical data.

Since gender is a sensitive attribute and we're just looking for any example, let's instead try to predict handedness. This is indicated by the attribute ```WritingPreference```.

Right now, pandas thinks the column can have any string value: when we convert it, it checks the existing values (```Left Hand```, ```Right hand``` and ```Either hand (No preference)```) and limits the column values to those two options (changing the datatype).

In [ ]:
wp_cat = people.WritingPreference.astype('category')
print(wp_cat.dtype)
print(wp_cat.cat.categories)

Note that we haven't changed the original data. To insert the categorized column back into the original dataframe, we just re-assign it.

In [ ]:
people.WritingPreference = people.WritingPreference.astype('category')

We can quickly check the class balance using the ```value_counts()``` function. (For a more fancy display, try the hist() function).

In [ ]:
people.WritingPreference.value_counts(normalize=True) 

# normalize=False will give you absolute counts

What does this tell us about the performance of the majority class baseline?

For many tasks (including classification with sklearn), we need integers instead of categorical values. Pandas actually uses integer codes behind the scenes for its categories and it's a simple matter to get a column of integers from a column of categorical data:

In [ ]:
people.WritingPreference.cat.codes

This allows us, for instance, to scatterplot the data using the categories for color.

You can add a cmap argument like ```cmap='copper'``` to change the colors. A [colormap](https://matplotlib.org/examples/color/colormaps_reference.html) maps a range of numeric values to a range of colors. I our case, we only have the values 0 and 1, so those get mapped to the extremes of the chosen colormap.

In [ ]:
sub = people[:500]
plt.scatter(sub.stature, sub.span, c=sub.WritingPreference.cat.codes, alpha=0.3);

Clearly, stature and span are not very predictive. Perhaps the measurements of the right arm will tell us a little more??

In [ ]:
sub = people[:500]
plt.scatter(sub.bicepscircumferenceflexed, sub.bideltoidbreadth, c=sub.WritingPreference.cat.codes, alpha=0.3);

Clearly, this is a difficult problem. It may even be impossible from the features we have. Let's try anyway.

### Classification

Running a classifier looks much the same as it did with a numpy array.

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

train = people[:4000]
test  = people[4000:]
# NB: We can split like this because we know the data is shuffled

cls = SVC()
cls.fit(train[['stature','span']], train.WritingPreference)

accuracy_score(cls.predict(test[['stature', 'span']]), test.WritingPreference)

Very slightly higher than the majority class (though your results may differ). Can we conclude that handedness can be predicted from height and span?

Let's see what we get for a kNN classifier on all measurements.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.metrics import accuracy_score

train = people[:4000]
test  = people[4000:]
# NB: We can split like this because we know the data is shuffled

traina, testa = train.iloc[:, 1:94], test.iloc[:, 1:94] # select all measurement columns

cls = KNN(n_neighbors=1)
cls.fit(traina, train.WritingPreference)

accuracy_score(cls.predict(testa), test.WritingPreference)

Lower than the majority class. Note that with the number of neigbhors at 1, kNN is likely to overfit. See what happens if you increase the number of neighbors.

At this point, we're in danger of multiple testing, so we should make a proper train/validation/test split. Can you see how you would do that?

As you can see, sklearn integrates beautifully with pandas, making our training and testing code even simpler. Not all libraries integrate this well with pandas; mlxtend, for instance, only inderstands numpy data.

Happily, pandas data contains numpy arrays in the background, and we can simply ask for those by retrieving the ```.values``` attribute.

In [ ]:
from mlxtend.plotting import plot_decision_regions

# Plot the decision boundary with the first 50 points in the test set
numpy_x = train[['stature','span']].values
numpy_y = train.WritingPreference.cat.codes.values

# This is necessary if pandas read the CSV files as integers
# (seems to depend on version/OS)
numpy_x = numpy_x.astype(float)

# Rebuild the classifier 
# (a classifier trained on pandas data doesn't interoperate well with pure numpy data)
tree = KNN(n_neighbors=2)
tree.fit(numpy_x, numpy_y)

plot_decision_regions(numpy_x[:25, :], numpy_y[:25], clf=tree);

## Final comments

As usual, there is a lot more to learn. A good place to start is the 10-minute quicktstart guide to pandas:
https://pandas.pydata.org/pandas-docs/stable/10min.html

One very useful feature we didn't mention is _grouping_ (which will be familiar if you've done a little SQL):
https://pandas.pydata.org/pandas-docs/stable/groupby.html

Here's a list of 12 random tips, which gives you a good idea of how far pandas can go:
https://www.analyticsvidhya.com/blog/2016/01/12-pandas-techniques-python-data-manipulation/

Next week, deep learning with _Keras_.